### PR TITLE
Make `aws_iam_policy_document` optional

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Empty `aws_iam_policy_document`

## why
* Create a role without any policy document

## references
* See #15

## test

```hcl
module "eks_iam_role" {
  # source = "cloudposse/eks-iam-role/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version     = "x.x.x"

  source = "git::https://github.com/cloudposse/terraform-aws-eks-iam-role.git?ref=null_aws_iam_policy_document"

  aws_account_number          = local.account_id
  eks_cluster_oidc_issuer_url = module.eks_cluster.eks_cluster_identity_oidc_issuer

  # Create a role for the service account named `autoscaler` in the Kubernetes namespace `kube-system`
  service_account_name      = "autoscaler"
  service_account_namespace = "kube-system"
}
```

### CODE REVIEW

**Comment by z0rc** [comment]
I tried this branch, and it didn't work. Sample code:
```terraform
module "vpc_cni_eks_iam_role" {
  source = "github.com/cloudposse/terraform-aws-eks-iam-role?ref=null_aws_iam_policy_document"

  stage                       = local.cluster_stage
  name                        = local.cluster_name
  service_account_namespace   = "kube-system"
  service_account_name        = "aws-node"
  eks_cluster_oidc_issuer_url = module.eks.eks_cluster_identity_oidc_issuer
  aws_account_number          = data.aws_caller_identity.current.account_id
}

resource "aws_iam_role_policy_attachment" "vpc_cni_eks_iam_role" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = module.vpc_cni_eks_iam_role.service_account_role_name
}
```
`terraform plan` produces:
```
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_cni_eks_iam_role/main.tf line 84, in resource "aws_iam_role_policy_attachment" "service_account":
│   84:   policy_arn = aws_iam_policy.service_account[each.value].arn
│     ├────────────────
│     │ aws_iam_policy.service_account is object with no attributes
│     │ each.value is "dev-01-aws-node@kube-system"
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_cni_eks_iam_role/outputs.tf line 27, in output "service_account_policy_name":
│   27:   value       = local.enabled ? values(aws_iam_policy.service_account)[0].name : null
│     ├────────────────
│     │ aws_iam_policy.service_account is object with no attributes
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_cni_eks_iam_role/outputs.tf line 32, in output "service_account_policy_id":
│   32:   value       = local.enabled ? values(aws_iam_policy.service_account)[0].id : null
│     ├────────────────
│     │ aws_iam_policy.service_account is object with no attributes
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_cni_eks_iam_role/outputs.tf line 37, in output "service_account_policy_arn":
│   37:   value       = local.enabled ? values(aws_iam_policy.service_account)[0].arn : null
│     ├────────────────
│     │ aws_iam_policy.service_account is object with no attributes
│
│ The given key does not identify an element in this collection value.
╵
```

**Comment by z0rc** [comment]
Errors after last commit:
```
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_cni_eks_iam_role/outputs.tf line 27, in output "service_account_policy_name":
│   27:   value       = local.enabled ? values(aws_iam_policy.service_account)[0].name : null
│     ├────────────────
│     │ aws_iam_policy.service_account is object with no attributes
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_cni_eks_iam_role/outputs.tf line 32, in output "service_account_policy_id":
│   32:   value       = local.enabled ? values(aws_iam_policy.service_account)[0].id : null
│     ├────────────────
│     │ aws_iam_policy.service_account is object with no attributes
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/vpc_cni_eks_iam_role/outputs.tf line 37, in output "service_account_policy_arn":
│   37:   value       = local.enabled ? values(aws_iam_policy.service_account)[0].arn : null
│     ├────────────────
│     │ aws_iam_policy.service_account is object with no attributes
│
│ The given key does not identify an element in this collection value.
╵
```

**Comment by z0rc** [comment]
Outputs need to be updated:
```diff
diff --git a/outputs.tf b/outputs.tf
index 2ac03b7..19aa48b 100755
--- a/outputs.tf
+++ b/outputs.tf
@@ -24,16 +24,16 @@ output "service_account_role_arn" {
 }

 output "service_account_policy_name" {
-  value       = local.enabled ? values(aws_iam_policy.service_account)[0].name : null
+  value       = local.enabled && var.aws_iam_policy_document != null ? values(aws_iam_policy.service_account)[0].name : null
   description = "IAM policy name"
 }

 output "service_account_policy_id" {
-  value       = local.enabled ? values(aws_iam_policy.service_account)[0].id : null
+  value       = local.enabled && var.aws_iam_policy_document != null ? values(aws_iam_policy.service_account)[0].id : null
   description = "IAM policy ID"
 }

 output "service_account_policy_arn" {
-  value       = local.enabled ? values(aws_iam_policy.service_account)[0].arn : null
+  value       = local.enabled && var.aws_iam_policy_document != null ? values(aws_iam_policy.service_account)[0].arn : null
   description = "IAM policy ARN"
 }
```

**Comment by Gowiem** [comment]
+1 to this work @nitrocode -- I'm running into this with a client and it feels wrong to have to create a dummy, empty policy 👍

**Comment by nitrocode** [comment]
@z0rc thanks for the suggestion above. Please check it while we wait for PR reviewers.

@Gowiem thanks for the encouragement!

**Review by Gowiem — APPROVED** [review]
LGTM, I'll hold off on merging until @z0rc verifies on his end.

**Review by z0rc — APPROVED** [review]
LGTM, thanks.

**Review by osterman — APPROVED** [review]

**Pull request merged**
