### PR TITLE
Refactor enable logic to use counts instead of `for_each`

### PR DESCRIPTION
**Pull request by elventear**
## what
Use `count` instead of `for_each` to manage if a resource is enabled or disabled.

## why

If any element of the service account name is not known at plan time, `for_each` would cause the plan to fail. 

The main advantage of `for_each` over `count` is stability when an item in a list is added or removed or the order of elements in a list changes. With `for_each`, only the changed item is affected, while with `count` other items can be affected by being moved to a different position in the list. This advantage is not applicable to this module because there is always only one item.

## note

This change will cause the IAM role to be deleted and recreated. If you have attached policies to the role outside of this module, you will need to reattach them.

### CODE REVIEW

**Comment by nitrocode** [comment]
@elventear thank you for the contribution! It's always refreshing to see new contributors.

While this PR may allow geting around the issue you're facing, it may disrupt current consumers of this module since we are changing from for_each to count.

Generally, we move from count to for_each so reordering doesn't trigger recreations of equivalent resources.

There must be an alternative. The error is thrown on the data aws iam policy document. Perhaps a `local.enabled` check could help?

```hcl
  for_each = local.enabled ? toset(compact([module.service_account_label.id])) : toset([])
```

Was it required to change the other for_eachs to count as well? I'm interested in seeing your exact inputs to reproduce this issue. If possible, it would be nice to see a test that can reproduce the error and then modify this module in such a way that will retain the for_each for backwards compatibility.

cc: @Nuru what do you think?

**Comment by elventear** [comment]
@nitrocode your suggestion does not fix the problem. I have tried various thing, like removing the `compact` function.

The issue does not show up in the `data` source because there is anything different for it, it happens to be the leaf in the  tree within the terraform execution plan. If I fix only the `data` the problem moves to the next dependency, the `aws_iam_role` `resource`. 

The issue here is that by design the `for_each`, within the terraform architecture, cannot determine the full state state until apply, creating this sort of issues. My guess is because it is the value of `module.service_account_label.id` depends on the execution of the module first, which has non straightforward execution:

```
  id       = local.id_length_limit != 0 && length(local.id_full) > local.id_length_limit ? local.id_short : local.id_full
```

**Comment by elventear** [comment]
I understand the issue with backwards compatibility but the problem is complete blocker for more general usage. The only two options I would have is either copy the contents within my own TF, or fork the module.

**Review by aknysh — DISMISSED** [review]

**Review by nitrocode — DISMISSED** [review]
Let's discuss this more with regard to backwards compatibility

**Comment by Nuru** [comment]
@elventear Thank you for bringing this to our attention. For most users, all of the elements of the service account name, and therefore the name itself, are known at plan time, so `for_each` is not an issue. But as you have experienced, this is not _always_ the case, and converting to `count` will fix that.

I made some changes for style and to cover some missing tests, and updated the PR description. I hope you don't mind that I added it to this PR rather than creating a separate one.

**Review by Nuru — APPROVED** [review]

**Pull request merged**
