### PR TITLE
feat: attachement of the managed policies fixes cloudposse/terraform-aws-eks-iam-role#41

### LINKED ISSUE #41: Auto policy attachmant akin to managed_policy_arns in aws-iam-role
### Describe the Feature

This would basically work like the `managed_policy_arns` argument in the aws-iam-role module, generating aws_iam_role_policy_attachments for every ARN on the list.

Example:
```
module "eks_iam_role_karpenter" {
  source  = "cloudposse/eks-iam-role/aws"
  version = "2.1.1"

  context = module.label_eks.context

  aws_account_number          = data.aws_caller_identity.current.id
  eks_cluster_oidc_issuer_url = module.eks_cluster.eks_cluster_identity_oidc_issuer

  service_account_name      = "karpenter"
  service_account_namespace = "karpenter"
  
  # new argument
  managed_policy_arns = ["arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser"]
}
```

### Expected Behavior

Auto generated aws policy attachments

### Use Case

Less boilerplate code

### Describe Ideal Solution

managed_policy_arns argument working just like in the aws-iam-policy module

### Alternatives Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by salemgolemugoo**
## what

Possibility to attach managed policies like in https://github.com/cloudposse/terraform-aws-iam-role

## why

* Be consistent with the existing modules
* Avoid boilerplate code to attach a managed policy via data resource

## references

closes cloudposse/terraform-aws-eks-iam-role#41

### CODE REVIEW

**Comment by salemgolemugoo** [comment]
@elventear please review

**Comment by Gowiem** [comment]
@salemgolemugoo Unfortunately, we need to run some automation to pass our tests. Mind doing the following locally, adding + committing the result, and pushing to your branch?

```
make init
make readme
```

Thanks!

**Comment by Nuru** [comment]
Closing this in favor of #58 only because the latter has the generated updates to documentation.

**Pull request closed without merging**
